[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 2400
    UnBondPeriodInEpochs = 1
    MinStepValue = "100000000000000000000"
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 320
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true
    StakeLimitPercentage = 1.0 #fraction of value 1 - 100%, for the time being no stake limit
    NodeLimitPercentage = 0.05 #fraction of value 0.1 - 10% (180*0.05=9)

[ESDTSystemSCConfig]
    BaseIssuingCost = "50000000000000000" #0.05 eGLD
    OwnerAddress = "erd17x5h63fgentz5302m9rd7ryttssttk68xtpr9qdztssw88vfs07s65w8dc"

[GovernanceSystemSCConfig]
    OwnerAddress = "erd1uwd7czafqa2eka354h8y9slx4t8da7sf3d0nce6yj3rnf72j63ns8v5uef" #should use a multisign contract instead of a wallet address
    MaxVotingDelayPeriodInEpochs = 30
    [GovernanceSystemSCConfig.V1]
        NumNodes           = 500
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = 400
        MinPassThreshold   = 300
        MinVetoThreshold   = 50
    [GovernanceSystemSCConfig.Active]
        ProposalCost       = "1000000000000000000000" #1000 eGLD
        LostProposalFee    = "10000000000000000000"   #10 eGLD
        MinQuorum          = 0.2  #fraction of value 0.2  - 20%
        MinPassThreshold   = 0.5  #fraction of value 0.5  - 50%
        MinVetoThreshold   = 0.33 #fraction of value 0.33 - 33%

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    MinStakeAmount = "1000000000000000000" #1 eGLD
    ConfigChangeAddress = "erd1tsgw76rcawsdp703qh25vezkpmley8xu6k6wx3jngru470rqu2rq5lqmjd" #should use a multisign contract instead of a wallet address

[DelegationSystemSCConfig]
    MinServiceFee  = 0
    MaxServiceFee  = 10000

# Changing this config is not backwards compatible
[SoftAuctionConfig]
    TopUpStep = "10000000000000000000" # 10 EGLD
    MinTopUp = "1000000000000000000" # 1 EGLD should be minimum
    MaxTopUp = "32000000000000000000000000" # 32 mil EGLD
    MaxNumberOfIterations = 100000 # 100k max number of iterations for soft auction config
